public class Constants {
    public static final String BASE_URL = "https://countries.trevorblades.com/";
    public static final String MESSAGE_SUCCESS_SHOULDRETURNSTATUS200ANDSUCCESMESSAGE = "{\"data\":{\"language\":{\"name\":\"Portuguese\",\"native\":\"Português\",\"rtl\":false}}}\n";
    public static final String MESSAGE_ERROR_SHOULDRETURNSTATUS400ANDERRORMESSAGECODEREQUIRED = "{\"errors\":[{\"message\":\"Field \\\"language\\\" argument \\\"code\\\" of type \\\"ID!\\\" is required, but it was not provided.\",\"locations\":[{\"line\":2,\"column\":5}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}}]}\n";
    public static final String MESSAGE_SUCCESS_SHOULDRETURNSTATUS200ANDMESSAGENOTCONTAINLANGUAGEPT = "{\"data\":{\"languages\":[{\"name\":\"Afrikaans\"},{\"name\":\"Amharic\"},{\"name\":\"Arabic\"},{\"name\":\"Aymara\"},{\"name\":\"Azerbaijani\"},{\"name\":\"Belarusian\"},{\"name\":\"Bulgarian\"},{\"name\":\"Bislama\"},{\"name\":\"Bengali\"},{\"name\":\"Bosnian\"},{\"name\":\"Catalan\"},{\"name\":\"Chamorro\"},{\"name\":\"Czech\"},{\"name\":\"Danish\"},{\"name\":\"German\"},{\"name\":\"Divehi\"},{\"name\":\"Dzongkha\"},{\"name\":\"Greek\"},{\"name\":\"English\"},{\"name\":\"Spanish\"},{\"name\":\"Estonian\"},{\"name\":\"Basque\"},{\"name\":\"Persian\"},{\"name\":\"Peul\"},{\"name\":\"Finnish\"},{\"name\":\"Fijian\"},{\"name\":\"Faroese\"},{\"name\":\"French\"},{\"name\":\"Irish\"},{\"name\":\"Galician\"},{\"name\":\"Guarani\"},{\"name\":\"Manx\"},{\"name\":\"Hebrew\"},{\"name\":\"Hindi\"},{\"name\":\"Croatian\"},{\"name\":\"Haitian\"},{\"name\":\"Hungarian\"},{\"name\":\"Armenian\"},{\"name\":\"Indonesian\"},{\"name\":\"Icelandic\"},{\"name\":\"Italian\"},{\"name\":\"Japanese\"},{\"name\":\"Georgian\"},{\"name\":\"Kongo\"},{\"name\":\"Kazakh\"},{\"name\":\"Greenlandic\"},{\"name\":\"Cambodian\"},{\"name\":\"Korean\"},{\"name\":\"Kurdish\"},{\"name\":\"Kirghiz\"},{\"name\":\"Latin\"},{\"name\":\"Luxembourgish\"},{\"name\":\"Lingala\"},{\"name\":\"Laotian\"},{\"name\":\"Lithuanian\"},{\"name\":\"Luba-Katanga\"},{\"name\":\"Latvian\"},{\"name\":\"Malagasy\"},{\"name\":\"Marshallese\"},{\"name\":\"Maori\"},{\"name\":\"Macedonian\"},{\"name\":\"Mongolian\"},{\"name\":\"Malay\"},{\"name\":\"Maltese\"},{\"name\":\"Burmese\"},{\"name\":\"Nauruan\"},{\"name\":\"Norwegian Bokmål\"},{\"name\":\"North Ndebele\"},{\"name\":\"Nepali\"},{\"name\":\"Dutch\"},{\"name\":\"Norwegian Nynorsk\"},{\"name\":\"Norwegian\"},{\"name\":\"South Ndebele\"},{\"name\":\"Chichewa\"},{\"name\":\"Occitan\"},{\"name\":\"Panjabi / Punjabi\"},{\"name\":\"Polish\"},{\"name\":\"Pashto\"},{\"name\":\"Portuguese\"},{\"name\":\"Quechua\"},{\"name\":\"Kirundi\"},{\"name\":\"Romanian\"},{\"name\":\"Russian\"},{\"name\":\"Rwandi\"},{\"name\":\"Sango\"},{\"name\":\"Sinhalese\"},{\"name\":\"Slovak\"},{\"name\":\"Slovenian\"},{\"name\":\"Samoan\"},{\"name\":\"Shona\"},{\"name\":\"Somalia\"},{\"name\":\"Albanian\"},{\"name\":\"Serbian\"},{\"name\":\"Swati\"},{\"name\":\"Southern Sotho\"},{\"name\":\"Swedish\"},{\"name\":\"Swahili\"},{\"name\":\"Tamil\"},{\"name\":\"Tajik\"},{\"name\":\"Thai\"},{\"name\":\"Tigrinya\"},{\"name\":\"Turkmen\"},{\"name\":\"Tswana\"},{\"name\":\"Tonga\"},{\"name\":\"Turkish\"},{\"name\":\"Tsonga\"},{\"name\":\"Ukrainian\"},{\"name\":\"Urdu\"},{\"name\":\"Uzbek\"},{\"name\":\"Venda\"},{\"name\":\"Vietnamese\"},{\"name\":\"Xhosa\"},{\"name\":\"Chinese\"},{\"name\":\"Zulu\"}]}}\n";
    public static final String MESSAGE_SUCCESS_SHOULDRETURNSTATUS400ANDERRORMESSAGEINVALIDJSON = "{\"errors\":[{\"message\":\"Syntax Error: Expected Name, found :\",\"locations\":[{\"line\":2,\"column\":32}],\"extensions\":{\"code\":\"GRAPHQL_PARSE_FAILED\"}}]}\n";
    public static final String MESSAGE_SUCCESS_PUT = "Registro alterado com sucesso";
}

